// Feel-lock: a snapshot of the compiled core rules (collision, ball physics,
// round flow, dash/deflect timing) and their order, so a change to how the ball
// feels can't slip in unnoticed. `npm run check` compares against the snapshot.
//
// Usage: npm run feel-lock:update   (rewrites tools/feel-lock.json)
//
// Changing the snapshot is a deliberate core change: the PR needs the
// `ball feel` label. See docs/development.md.
import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { pathToFileURL } from "node:url";
import overpy from "overpy";

const root = resolve(import.meta.dirname, "..");
export const snapshotPath = resolve(root, "tools/feel-lock.json");

// Every rule and subroutine in these files is locked, including ones added later.
const LOCKED_FILES = ["rules/06-round-flow.opy", "rules/08-collision.opy", "rules/09-ball-physics.opy"];
// Plus these rules from other files (dash/deflect timing in 05-controls).
const LOCKED_RULES = [
  "Controls - primary fire triggers dash",
  "Controls - secondary fire triggers deflect",
  "Controls - Dash slow (gravity shift)",
  "Controls - Shorten deflect length",
  "Controls - anti-rubberbanding button lock",
  "Controls - Ability 1 dash queue",
  "Controls - Ability 2 deflect queue",
  "Controls - Dash cooldown",
  "Control - Dash reset",
];

// The full OverPy compile result, with `result` normalized to LF line endings.
export async function compile() {
  await overpy.readyPromise;
  const source = await readFile(resolve(root, "src/main.opy"), "utf8");
  const compiled = await overpy.compile(source, "en-US", resolve(root, "src"), "main.opy");
  return { ...compiled, result: compiled.result.replace(/\r\n/g, "\n") };
}

export async function compileSource() {
  return (await compile()).result;
}

// Rule names as they appear in-game: `rule "..."` and a def's `@Name "..."`.
async function lockedNames() {
  const names = new Set(LOCKED_RULES);
  for (const file of LOCKED_FILES) {
    const source = await readFile(resolve(root, "src", file), "utf8");
    for (const [, name] of source.matchAll(/^(?:rule |\s+@Name )("(?:[^"\\]|\\.)*")/gm)) {
      names.add(JSON.parse(name));
    }
  }
  return names;
}

// Splits compiled Workshop code into its rules, in list order.
function parseRules(compiled) {
  const rules = [];
  let current = null;
  for (const line of compiled.split("\n")) {
    const start = line.match(/^(?:disabled )?rule \(("(?:[^"\\]|\\.)*")\) \{$/);
    if (start) {
      current = { name: JSON.parse(start[1]), code: [line] };
      rules.push(current);
    } else if (current) {
      current.code.push(line);
      if (line === "}") current = null;
    }
  }
  return rules;
}

// The locked rules, in list order, each with its full compiled text.
export async function lockedRules(compiled) {
  const names = await lockedNames();
  const rules = parseRules(compiled).filter((rule) => names.has(rule.name));
  const found = new Map();
  for (const rule of rules) found.set(rule.name, (found.get(rule.name) ?? 0) + 1);
  for (const name of names) {
    if (found.get(name) !== 1) {
      throw new Error(`feel-lock: expected exactly one compiled rule named "${name}", found ${found.get(name) ?? 0}`);
    }
  }
  return rules;
}

export async function readSnapshot() {
  return JSON.parse(await readFile(snapshotPath, "utf8")).rules;
}

// Returns a list of human-readable differences (empty when the snapshot matches).
export function compareSnapshot(expected, actual) {
  const problems = [];
  const expectedByName = new Map(expected.map((rule) => [rule.name, rule]));
  const actualNames = new Set(actual.map((rule) => rule.name));
  for (const rule of expected) {
    if (!actualNames.has(rule.name)) problems.push(`removed or renamed: "${rule.name}"`);
  }
  for (const rule of actual) {
    const locked = expectedByName.get(rule.name);
    if (!locked) problems.push(`new locked rule: "${rule.name}"`);
    else if (locked.code.join("\n") !== rule.code.join("\n")) problems.push(`code changed: "${rule.name}"`);
  }
  const expectedOrder = expected.map((rule) => rule.name).filter((name) => actualNames.has(name));
  const actualOrder = actual.map((rule) => rule.name).filter((name) => expectedByName.has(name));
  if (expectedOrder.join("\n") !== actualOrder.join("\n")) problems.push("the order of the locked rules changed");
  return problems;
}

async function update() {
  const rules = await lockedRules(await compileSource());
  const snapshot = {
    _comment: "Generated by `npm run feel-lock:update`. Do not edit by hand. A PR that changes this file changes ball feel and needs the `ball feel` label.",
    rules,
  };
  await writeFile(snapshotPath, JSON.stringify(snapshot, null, 2) + "\n", "utf8");
  console.log(`Wrote tools/feel-lock.json (${rules.length} locked rules)`);
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  await update();
}
